name: Cloudformation_dynamo

on:
  workflow_dispatch:

    inputs:
 
      BucketName:
        description: 'bucket name'
        required: true
        default: 'reeceve-test-waseem'
      HashKeyElementName:
        description: 'dynamo db primary id'
        required: true
        default: 'id'
    
    

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  dynamo-deploy:
    runs-on: ubuntu-latest
    #environment: Test
    
    steps:

      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: cloudformation-demo
          template: iac/dynomodb.yml
          parameter-overrides: >-
            BucketName=${{ inputs.BucketName }},
            HashKeyElementName=${{ inputs.HashKeyElementName }}


          no-fail-on-empty-changeset: "1"



            #"HashKeyElementType=${{ inputs.HashKeyElementType }}",
            #"ReadCapacityUnits=${{ inputs.ReadCapacityUnits }}",
            #"WriteCapacityUnits=${{ inputs.WriteCapacityUnits }}".
            #"PointInTimeRecoverySpecification=${{ inputs.PointInTimeRecoverySpecification }}"
