name: Lamdafunction 

on:
  workflow_dispatch:

    inputs:
      EnvName:
        description: 'dev | uat | test'
        required: true
        default: 'test'

      BucketName:
        description: 'bucket name'
        required: true
        default:  "receevebucket-name"

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: build
      run: npm i
      
    - name: Install zip
      uses: montudor/action-zip@v1

    - name: Zip output
      run: zip -qq -r ./function.zip .
      #working-directory: artifact/publish
      
   # - name: Copy Cloudformation Template
   #   run: cd iac
    - uses: actions/upload-artifact@v3
      with:
        name: iac
        path: ./iac
  
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Upload to S3
      run: |
       #aws lambda update-function-code --function-name lambda-function- --zip-file fileb://function.zip --s3-bucket receevebucket-name

      
  test-deploy-env:
    runs-on: ubuntu-latest
    environment: test
    needs: build
    
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: iac
          path: ./iac
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
          
      - name: list folder
        run: ls -altr
      
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          stack-name: cloudformationlamda
          template-file: .iac/receevelamdafunction.yml
          parameter-overrides: EnvName=test-deploy-env
          aws-region: us-east-1
          capabilities: CAPABILITY_NAMED_IAM

          
  
